FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/processor ./apps/processor
COPY packages ./packages

ENV NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
ENV NEW_RELIC_LOG=stdout

RUN npm install
RUN npm run db:generate

RUN npm run build

CMD ["npm", "run", "start-processor"]