FROM python:3.8.12
WORKDIR /app
COPY apps/flask-worker ./apps/flask-worker
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
CMD ["gunicorn", "-w 1", "-b 0.0.0.0:5000", "--access-logfile", "logs/access.log", "--error-logfile", "logs/error.log", "app:app"]