FROM python:3.8.12
WORKDIR /app
COPY apps/flask-worker ./apps/flask-worker
RUN pip install --no-cache-dir -r apps/flask-worker/app/requirements.txt
EXPOSE 5000
CMD ["gunicorn", "-w 1", "-b 0.0.0.0:5000", "--access-logfile", "apps/flask-worker/app/logs/access.log", "--error-logfile","apps/flask-worker/app/logs/error.log", "app:app"]