FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/dashboard-app ./apps/dashboard-app
COPY packages ./packages

ENV NODE_ENV=production

RUN npm install
RUN npm run db:generate

RUN npm run build

EXPOSE 4000

CMD ["npm", "run", "start-dashboard-app"]